import { Component, lazy, Suspense, useCallback, useEffect, useRef, useState } from 'react';
import { ArrowDownUp, ArrowRight, Check, ChevronDown, ChevronRight, Clapperboard, Folder, Grid2X2, Home, Image, List, Loader2, MoreHorizontal, Plus, Search, Settings2, Sparkles, Trash2, Type, Video, X, Pencil, CheckCircle2, CircleHelp, LogOut, PanelLeftClose, PanelLeftOpen } from 'lucide-react';
import { api } from './api';
import type { AppStatus, CanvasNode, NodeKind, Project, ProjectDetail } from '../shared/types';
import SettingsDialog from './components/SettingsDialog';
import type { ReactNode } from 'react';
const CanvasWorkspace=lazy(()=>import('./components/CanvasWorkspace'));
const AgentWorkspace=lazy(()=>import('./components/AgentWorkspace'));
const emptyStatus:AppStatus={authenticated:true,authRequired:false,version:'1.0.0',services:{text:{configured:false,model:''},image:{configured:false,model:''},video:{configured:false,model:''}}};
type Page='home'|'projects'|'agent'|'canvas';
function parseRoute(){const path=window.location.pathname;return {page:(path.startsWith('/canvas/')?'canvas':path.startsWith('/agent')?'agent':path.startsWith('/projects')?'projects':'home') as Page,id:path.startsWith('/canvas/')?decodeURIComponent(path.split('/')[2]):new URLSearchParams(location.search).get('project')};}
export default function App(){
 const [route,setRoute]=useState(parseRoute),[projects,setProjects]=useState<Project[]>([]),[status,setStatus]=useState(emptyStatus),[loaded,setLoaded]=useState(false),[error,setError]=useState(''),[settings,setSettings]=useState(false),[toast,setToast]=useState(''),[creating,setCreating]=useState(false),[refreshKey,setRefreshKey]=useState(0),[sidebarCollapsed,setSidebarCollapsed]=useState(false),[help,setHelp]=useState(false);
 const toastTimer=useRef<ReturnType<typeof setTimeout>|null>(null);
 const notify=useCallback((message:string)=>{setToast(message);if(toastTimer.current)clearTimeout(toastTimer.current);toastTimer.current=setTimeout(()=>setToast(''),4500)},[]);
 const navigate=useCallback((page:Page,id?:string)=>{const url=page==='home'?'/':page==='canvas'?`/canvas/${id}`:page==='agent'&&id?`/agent?project=${id}`:`/${page}`;history.pushState({},'',url);setRoute({page,id:id||null});window.scrollTo(0,0)},[]);
 const loadProjects=useCallback(async()=>{try{const r=await api<{projects:Project[]}>('/projects');setProjects(r.projects);setError('')}catch(e){setError((e as Error).message)}},[]);
 const loadStatus=useCallback(async()=>{try{const value=await api<AppStatus>('/status');setStatus(value);if(value.authenticated)await loadProjects()}catch(e){setError((e as Error).message)}finally{setLoaded(true)}},[loadProjects]);
 useEffect(()=>{void loadStatus();const pop=()=>setRoute(parseRoute());window.addEventListener('popstate',pop);return()=>{window.removeEventListener('popstate',pop);if(toastTimer.current)clearTimeout(toastTimer.current)}},[loadStatus]);
 const changed=useCallback(()=>{void loadProjects();setRefreshKey(k=>k+1)},[loadProjects]);
 const createProject=async(kind?:NodeKind,template?:{name:string;prompt:string})=>{if(creating)return;setCreating(true);try{const {project}=await api<{project:Project}>('/projects',{method:'POST',body:JSON.stringify({name:template?.name||'未命名作品'})});if(kind||template){const {canvas}=await api<ProjectDetail>(`/projects/${project.id}`);const node:CanvasNode={id:crypto.randomUUID(),type:'creative',position:{x:160,y:120},data:{kind:kind||'text',title:template?.name||({text:'创作灵感',image:'图片生成',video:'视频生成'}[kind||'text']),prompt:template?.prompt||'',aspectRatio:'16:9',duration:5}};await api(`/projects/${project.id}/canvas`,{method:'PUT',body:JSON.stringify({...canvas,nodes:[node]})})}await loadProjects();navigate('canvas',project.id)}catch(e){notify((e as Error).message)}finally{setCreating(false)}};
 const openAgent=()=>navigate('agent',route.id||undefined);
 if(loaded&&status.authRequired&&!status.authenticated)return <Login onSuccess={loadStatus}/>;
 return <div className={`app-shell ${sidebarCollapsed?'sidebar-collapsed':''} ${route.page==='canvas'?'is-canvas':''}`}>
  {route.page!=='canvas'&&<aside className="sidebar">
   <button className="brand" onClick={()=>navigate('home')} aria-label="LibTV Studio 首页"><span className="brand-mark"><span/><span/><span/></span><span className="brand-word">LibTV<span>STUDIO</span></span></button>
   <button className="new-project-btn" onClick={()=>void createProject()} disabled={creating}><Plus size={18}/><span>{creating?'正在创建…':'新建项目'}</span></button>
   <nav className="main-nav" aria-label="主导航"><button className={route.page==='home'?'active':''} onClick={()=>navigate('home')}><Home size={18}/><span>首页</span></button><button className={route.page==='projects'?'active':''} onClick={()=>navigate('projects')}><Folder size={18}/><span>项目</span><span className="nav-count">{projects.length}</span></button><button className={route.page==='agent'?'active':''} onClick={()=>navigate('agent')}><Sparkles size={18}/><span>LibTV Agent</span><span className="beta-tag">AI</span></button></nav>
   <div className="sidebar-recents"><div className="sidebar-section-label">最近打开</div>{projects.slice(0,5).map(project=><button key={project.id} title={project.name} onClick={()=>navigate('canvas',project.id)}><span className="recent-dot"/><span>{project.name}</span></button>)}{!projects.length&&<span className="sidebar-empty">你的作品将出现在这里</span>}</div>
   <div className="sidebar-bottom"><div className="workspace-card"><span className="workspace-icon">L</span><div><strong>我的创作空间</strong><span><i/> {status.services.text.configured?'AI 服务已配置':'本地工作区'}</span></div><ChevronDown size={14}/></div><div className="sidebar-utilities"><button onClick={()=>setSettings(true)} title="服务设置" aria-label="服务设置"><Settings2 size={17}/><span>设置</span></button><button onClick={()=>setHelp(true)} title="使用指南" aria-label="使用指南"><CircleHelp size={17}/></button><button className="sidebar-toggle" onClick={()=>setSidebarCollapsed(v=>!v)} aria-label={sidebarCollapsed?'展开侧边栏':'收起侧边栏'}>{sidebarCollapsed?<PanelLeftOpen size={17}/>:<PanelLeftClose size={17}/>}</button></div></div>
  </aside>}
  <main className="main-content">
   {route.page!=='canvas'&&<header className="topbar"><div className="breadcrumb"><span>工作空间</span><ChevronRight size={13}/><strong>{{home:'首页',projects:'项目',agent:'LibTV Agent',canvas:'画布'}[route.page]}</strong></div><div className="topbar-right"><button className="connection-chip" onClick={()=>setSettings(true)}><i className={status.services.text.configured?'online':''}/>{status.services.text.configured?'模型已配置':'连接 AI 服务'}<ChevronRight size={12}/></button><span className="avatar" title="我的创作空间">L</span></div></header>}
   {!loaded?<div className="loading-state"><Loader2 className="spin"/>正在打开工作空间…</div>:error?<div className="empty-state error-state"><CircleHelp size={32}/><h2>暂时无法打开工作空间</h2><p>{error}</p><button className="primary-btn" onClick={()=>void loadStatus()}>重新连接</button></div>:<WorkspaceBoundary key={route.page}><Suspense fallback={<div className="loading-state"><Loader2 className="spin"/>正在打开创作工具…</div>}>
    {route.page==='home'&&<HomePage projects={projects} creating={creating} onCreate={createProject} onOpen={id=>navigate('canvas',id)} onProjects={()=>navigate('projects')} onAgent={()=>navigate('agent')}/>}
    {route.page==='projects'&&<ProjectsPage projects={projects} onCreate={()=>void createProject()} onOpen={id=>navigate('canvas',id)} onChanged={changed} notify={notify}/>}
    {route.page==='canvas'&&route.id&&<CanvasWorkspace key={route.id} projectId={route.id} refreshKey={refreshKey} onProjectChange={changed} onOpenAgent={openAgent} onSettings={()=>setSettings(true)} onBack={()=>navigate('projects')} notify={notify}/>}
    {route.page==='agent'&&<AgentWorkspace projectId={route.id} onSelectProject={id=>navigate('agent',id)} onOpenCanvas={id=>navigate('canvas',id)} onSettings={()=>setSettings(true)} notify={notify} refreshKey={refreshKey} onProjectChange={changed}/>}
   </Suspense></WorkspaceBoundary>}
  </main>
  {settings&&<SettingsDialog status={status} onClose={()=>setSettings(false)} onSaved={value=>{setStatus(value);changed();notify('服务设置已保存')}} notify={notify}/>}
  {help&&<div className="modal-backdrop" onClick={()=>setHelp(false)}><section className="dialog help-dialog" role="dialog" aria-modal="true" aria-label="使用指南" onClick={e=>e.stopPropagation()}><button className="dialog-close icon-btn" onClick={()=>setHelp(false)} aria-label="关闭"><X size={20}/></button><span className="eyebrow">开始创作</span><h2>从想法，到你的下一帧。</h2><ol><li><strong>新建一个项目</strong><p>在画布中添加文本、图片或视频节点，也可以上传自己的素材。</p></li><li><strong>连接你的创作流程</strong><p>拖动节点端口建立引用，在右侧编辑提示词、比例和模型。</p></li><li><strong>与 Agent 一起创作</strong><p>选择一个 Skill 或直接描述想法，让 Agent 帮你规划分镜，再回到画布继续调整。</p></li><li><strong>保存并继续</strong><p>画布自动保存。项目页可以查找、重命名和重新打开作品。</p></li></ol><button className="primary-btn" onClick={()=>{setHelp(false);setSettings(true)}}>配置 AI 服务 <ArrowRight size={16}/></button></section></div>}
  {toast&&<div className="toast" role="status"><CheckCircle2 size={17}/>{toast}<button onClick={()=>setToast('')} aria-label="关闭通知"><X size={14}/></button></div>}
 </div>
}
const templates=[{name:'产品广告分镜',tag:'COMMERCIAL',image:'product',description:'让产品的每一个细节，都成为主角。',prompt:'请为一款新上市的香水规划 15 秒产品广告，分为 3 个镜头。每个镜头写出画面、运镜、光线和用于图像生成的提示词，风格克制、自然、具有电影质感。'}, {name:'电影感短片',tag:'STORYTELLING',image:'landscape',description:'把一句灵感，展开成一个故事。',prompt:'请为“独自旅行的人，在日落前抵达海边”规划一条 3 镜头电影感短片，包含简短剧本、每个镜头的画面描述和运镜，保持角色与色调一致。'}, {name:'视觉创意实验',tag:'EXPERIMENTAL',image:'abstract',description:'打破常规，探索画面的另一种可能。',prompt:'请策划一组以“重力消失的瞬间”为主题的超现实视觉，给出 3 个不同镜头的构图、材质、色彩与动态图像提示词。'}];
function HomePage({projects,creating,onCreate,onOpen,onProjects,onAgent}:{projects:Project[];creating:boolean;onCreate:(kind?:NodeKind,template?:{name:string;prompt:string})=>Promise<void>;onOpen:(id:string)=>void;onProjects:()=>void;onAgent:()=>void}){
 return <div className="home-page page-container"><div className="page-intro"><div><div className="eyebrow">YOUR CREATIVE SPACE</div><h1>每一个想法，都值得被看见<span>。</span></h1></div><span className="intro-note">灵感在此，创作不止。</span></div>
 <div className="creation-hero"><button className="canvas-launch" onClick={()=>void onCreate()} disabled={creating}><div className="canvas-orbit orbit-one"/><div className="canvas-orbit orbit-two"/><span className="canvas-launch-plus">{creating?<Loader2 className="spin" size={30}/>:<Plus size={32} strokeWidth={1.5}/>}</span><h2>新建画布创作</h2><p>自由连接文本、图片与视频，让灵感有序展开</p><span className="hero-bottom"><span>无限画布</span><span>自由编排</span><span>自动保存</span></span></button><button className="agent-launch" onClick={onAgent}><div className="agent-constellation"><div className="constellation-line"/><span className="star-center"><Sparkles size={29} strokeWidth={1.4}/></span><span className="star-mini star-a"><Type size={15}/></span><span className="star-mini star-b"><Image size={15}/></span><span className="star-mini star-c"><Video size={15}/></span></div><span className="agent-launch-label">LibTV Agent <span className="beta-tag">AI</span></span><p>把灵感交给你的创作搭档</p><span className="text-link">开始对话 <ArrowRight size={15}/></span></button></div>
 <div className="quick-tools">{[{kind:'text' as const,label:'文本创作',desc:'剧本 · 提示词',Icon:Type},{kind:'image' as const,label:'图片生成',desc:'让想象变成画面',Icon:Image},{kind:'video' as const,label:'视频生成',desc:'赋予画面生命力',Icon:Video}].map(({kind,label,desc,Icon})=><button key={kind} onClick={()=>void onCreate(kind)}><span className={`tool-icon ${kind}`}><Icon size={21} strokeWidth={1.5}/></span><span><strong>{label}</strong><small>{desc}</small></span><ChevronRight size={15}/></button>)}<button onClick={onAgent}><span className="tool-icon agent"><Sparkles size={21} strokeWidth={1.5}/></span><span><strong>智能分镜</strong><small>从故事到镜头</small></span><ChevronRight size={15}/></button></div>
 <section className="home-section"><div className="section-heading"><h2>最近项目 <span>{projects.length ? projects.length : ''}</span></h2><button className="quiet-btn" onClick={onProjects}>全部项目 <ArrowRight size={15}/></button></div>{projects.length?<div className="project-grid recent-project-grid">{projects.slice(0,3).map(p=><ProjectCard key={p.id} project={p} onOpen={()=>onOpen(p.id)}/>)}</div>:<div className="first-project-empty"><span className="empty-canvas-art"><span/><span/><span/></span><div><strong>留一张画布，给你的第一个想法。</strong><p>创建的项目会自动保存在这里，随时回来继续创作。</p></div><button className="secondary-btn" onClick={()=>void onCreate()}><Plus size={16}/>创建项目</button></div>}</section>
 <section className="home-section"><div className="section-heading"><div><h2>给灵感一个起点</h2><p>从一个方向出发，创作属于你的画面</p></div><span className="section-caption">创作模板 · 随心改写</span></div><div className="template-grid">{templates.map(t=><button className="template-card" key={t.name} onClick={()=>void onCreate('text',t)}><div className={`template-art art-${t.image}`}><img src={`/art/${t.image}.svg`} alt={t.name+'创作主题插画'}/><span>{t.tag}</span><i><ArrowRight size={17}/></i></div><div className="template-caption"><h3>{t.name}</h3><p>{t.description}</p></div></button>)}</div></section>
 <footer className="workspace-footer"><span>LibTV Studio</span><span>让创作，更专注于表达。</span></footer></div>
}
function ProjectCard({project,onOpen,menu}:{project:Project;onOpen:()=>void;menu?:React.ReactNode}){return <article className="project-card"><button className="project-preview" onClick={onOpen} aria-label={`打开项目 ${project.name}`}>{project.coverUrl?<img src={project.coverUrl} alt={project.name}/>:<div className="project-diagram"><span className="mini-node mini-text"><Type size={13}/><i/><i/><i/></span><span className="mini-edge"/><span className="mini-node mini-media"><Clapperboard size={24}/></span></div>}<span className="project-node-badge">{project.nodeCount} 个节点</span><span className="preview-open"><ArrowRight size={18}/></span></button><div className="project-info"><button onClick={onOpen}><h3>{project.name}</h3><p>{formatDate(project.updatedAt)}编辑</p></button>{menu}</div></article>}
function ProjectsPage({projects,onCreate,onOpen,onChanged,notify}:{projects:Project[];onCreate:()=>void;onOpen:(id:string)=>void;onChanged:()=>void;notify:(message:string)=>void}){
 const [search,setSearch]=useState(''),[view,setView]=useState<'grid'|'list'>('grid'),[sort,setSort]=useState('updated'),[menu,setMenu]=useState<string|null>(null),[edit,setEdit]=useState<Project|null>(null),[remove,setRemove]=useState<Project|null>(null),[name,setName]=useState(''),[busy,setBusy]=useState(false);
 const filtered=projects.filter(p=>p.name.toLocaleLowerCase().includes(search.toLocaleLowerCase())).sort((a,b)=>sort==='name'?a.name.localeCompare(b.name,'zh-CN'):b.updatedAt.localeCompare(a.updatedAt));
 useEffect(()=>{const close=()=>setMenu(null);window.addEventListener('click',close);return()=>window.removeEventListener('click',close)},[]);
 const save=async()=>{if(!edit||!name.trim())return;setBusy(true);try{await api(`/projects/${edit.id}`,{method:'PATCH',body:JSON.stringify({name:name.trim()})});setEdit(null);onChanged();notify('项目已重命名')}catch(e){notify((e as Error).message)}finally{setBusy(false)}};
 const deleteProject=async()=>{if(!remove)return;setBusy(true);try{await api(`/projects/${remove.id}`,{method:'DELETE'});setRemove(null);onChanged();notify('项目已删除')}catch(e){notify((e as Error).message)}finally{setBusy(false)}};
 const actions=(p:Project)=><div className="project-actions"><button className="icon-btn" aria-label={`${p.name}的更多操作`} onClick={e=>{e.stopPropagation();setMenu(menu===p.id?null:p.id)}}><MoreHorizontal size={20}/></button>{menu===p.id&&<div className="dropdown-menu"><button onClick={()=>{setEdit(p);setName(p.name)}}><Pencil size={14}/>重命名</button><button className="danger-text" onClick={()=>setRemove(p)}><Trash2 size={14}/>删除项目</button></div>}</div>;
 return <div className="projects-page page-container"><div className="page-intro"><div><div className="eyebrow">MY PROJECTS</div><h1>你的作品，都在这里<span>。</span></h1><p className="page-description">每一次探索，都值得继续。</p></div><button className="primary-btn" onClick={onCreate}><Plus size={18}/>新建项目</button></div><div className="project-filters"><div className="project-tab">全部项目 <span>{projects.length}</span></div><div className="project-filter-tools"><label className="search-field"><Search size={16}/><input placeholder="搜索项目" value={search} onChange={e=>setSearch(e.target.value)} aria-label="搜索项目"/>{search&&<button onClick={()=>setSearch('')} aria-label="清空搜索"><X size={14}/></button>}</label><label className="sort-control"><ArrowDownUp size={15}/><select aria-label="项目排序" value={sort} onChange={e=>setSort(e.target.value)}><option value="updated">最近编辑</option><option value="name">项目名称</option></select></label><div className="view-toggle"><button className={view==='grid'?'active':''} onClick={()=>setView('grid')} aria-label="网格视图"><Grid2X2 size={16}/></button><button className={view==='list'?'active':''} onClick={()=>setView('list')} aria-label="列表视图"><List size={17}/></button></div></div></div>
 {filtered.length?view==='grid'?<div className="project-grid">{filtered.map(p=><ProjectCard key={p.id} project={p} onOpen={()=>onOpen(p.id)} menu={actions(p)}/>)}</div>:<div className="project-list"><div className="project-list-head"><span>项目名称</span><span>节点数量</span><span>最后编辑</span><span/></div>{filtered.map(p=><div className="project-list-row" key={p.id}><button onClick={()=>onOpen(p.id)}><span className="list-thumb">{p.coverUrl?<img src={p.coverUrl} alt=""/>:<Clapperboard size={20}/>}</span><strong>{p.name}</strong></button><span>{p.nodeCount} 个节点</span><span>{formatDate(p.updatedAt)}</span>{actions(p)}</div>)}</div>:<div className="empty-state"><div className="empty-icon"><Folder size={32} strokeWidth={1}/></div><h2>{search?'没有找到这个项目':'你的创作空间，准备好了'}</h2><p>{search?'试试其他关键词，或创建一个新项目。':'新建一张画布，让第一个想法在这里发生。'}</p><button className="primary-btn" onClick={search?()=>setSearch(''):onCreate}>{search?'查看全部项目':<><Plus size={17}/>创建第一个项目</>}</button></div>}
 {edit&&<div className="modal-backdrop"><form className="dialog compact-dialog" onSubmit={e=>{e.preventDefault();void save()}}><h2>重命名项目</h2><label className="field-label" htmlFor="project-name">项目名称</label><input id="project-name" autoFocus maxLength={100} value={name} onChange={e=>setName(e.target.value)} className="form-input"/><div className="dialog-actions"><button type="button" className="secondary-btn" onClick={()=>setEdit(null)}>取消</button><button className="primary-btn" disabled={busy||!name.trim()}>{busy?<Loader2 size={16} className="spin"/>:<Check size={16}/>}保存</button></div></form></div>}
 {remove&&<div className="modal-backdrop"><section className="dialog compact-dialog" role="dialog" aria-modal="true" aria-label="删除项目"><span className="delete-icon"><Trash2 size={22}/></span><h2>删除「{remove.name}」？</h2><p className="dialog-description">项目中的画布、会话和素材也会一并删除，此操作无法撤销。</p><div className="dialog-actions"><button className="secondary-btn" onClick={()=>setRemove(null)}>取消</button><button className="danger-btn" disabled={busy} onClick={()=>void deleteProject()}>{busy?'正在删除…':'删除项目'}</button></div></section></div>}
 </div>
}
function Login({onSuccess}:{onSuccess:()=>Promise<void>}){const [password,setPassword]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);return <div className="login-screen"><form className="dialog" onSubmit={async e=>{e.preventDefault();setBusy(true);try{await api('/auth/login',{method:'POST',body:JSON.stringify({password})});await onSuccess()}catch(err){setError((err as Error).message)}finally{setBusy(false)}}}><span className="eyebrow">LIBTV STUDIO</span><h1>回到你的创作空间。</h1><p>输入工作区访问密码，继续创作。</p><label className="field-label" htmlFor="access-password">访问密码</label><input id="access-password" type="password" autoComplete="current-password" className="form-input" value={password} onChange={e=>setPassword(e.target.value)} required/>{error&&<div className="form-error">{error}</div>}<button className="primary-btn" disabled={busy}>{busy?'正在验证…':'进入工作区'}<ArrowRight size={16}/></button></form></div>}
function formatDate(value:string){const time=new Date(value),diff=Date.now()-time.getTime();if(diff<60000)return '刚刚';if(diff<3600000)return `${Math.floor(diff/60000)} 分钟前`;if(diff<86400000)return `${Math.floor(diff/3600000)} 小时前`;return time.toLocaleDateString('zh-CN',{month:'long',day:'numeric'});}

class WorkspaceBoundary extends Component<{children:ReactNode},{failed:boolean}>{
 state={failed:false};
 static getDerivedStateFromError(){return {failed:true}}
 render(){return this.state.failed?<div className="empty-state error-state"><CircleHelp size={32}/><h2>页面暂时未能打开</h2><p>应用可能刚刚更新，请重新加载后继续。已保存的项目不会丢失。</p><button className="primary-btn" onClick={()=>location.reload()}>重新加载</button></div>:this.props.children}
}
