// All provider responses in this file come from explicit local test servers.
// No real model credentials or paid generation endpoints are used by these tests.
import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, rmSync, readFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { createServer } from 'node:http';
import type { AddressInfo } from 'node:net';
import { createApp } from '../server/app';
import { Store } from '../server/store';
import { Configuration } from '../server/config';
import { JobEngine } from '../server/jobs';
import { chat } from '../server/providers';
import type { CanvasDocument } from '../shared/types';

const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a1Z0AAAAASUVORK5CYII=','base64');
async function fixture(env:NodeJS.ProcessEnv={}){const dir=mkdtempSync(path.join(tmpdir(),'libtv-test-'));const runtime=createApp({dataDir:dir,env,startJobs:false});const server=runtime.app.listen(0,'127.0.0.1');await new Promise<void>(r=>server.once('listening',r));const base=`http://127.0.0.1:${(server.address() as AddressInfo).port}`;
  return {...runtime,dir,base,request:async(url:string,method='GET',body?:unknown,cookie?:string)=>{const response=await fetch(base+url,{method,headers:{...(body instanceof FormData?{}:{'Content-Type':'application/json'}),...(cookie?{Cookie:cookie}:{})},body:body===undefined?undefined:body instanceof FormData?body:JSON.stringify(body)});return {status:response.status,body:await response.json(),response}},close:async()=>{runtime.jobs.stop();await new Promise<void>(r=>server.close(()=>r()));runtime.close();rmSync(dir,{recursive:true,force:true})}};
}
const node=(id='text-one')=>({id,type:'creative' as const,position:{x:33,y:74},data:{kind:'text' as const,title:'镜头一',prompt:'拍摄一杯咖啡',text:'开场'}});
const canvas=(nodes=[node()]):CanvasDocument=>({nodes,edges:[],viewport:{x:12,y:50,zoom:.8},version:0});
async function until(check:()=>boolean){for(let i=0;i<100;i++){if(check())return;await new Promise(r=>setTimeout(r,20))}throw new Error('Timed out waiting for local test job')}

test('project lifecycle persists canvas, validates optimistic version and survives reopening SQLite',async()=>{const f=await fixture();try{
  const created=await f.request('/api/projects','POST',{name:'咖啡广告'});assert.equal(created.status,201);const id=created.body.project.id;
  const saved=await f.request(`/api/projects/${id}/canvas`,'PUT',canvas());assert.equal(saved.status,200);assert.equal(saved.body.canvas.version,1);
  assert.equal((await f.request(`/api/projects/${id}/canvas`,'PUT',canvas())).status,409);
  const second=await f.request('/api/projects','POST',{name:'独立项目'});assert.equal((await f.request(`/api/projects/${second.body.project.id}`)).body.canvas.nodes.length,0);
  assert.equal((await f.request(`/api/projects/${id}`,'PATCH',{name:'更新后的广告'})).body.project.name,'更新后的广告');
  const reopened=new Store(f.dir);assert.equal(reopened.canvas(id).nodes[0].position.x,33);assert.equal(reopened.canvas(id).viewport.zoom,.8);reopened.close();
  assert.equal((await f.request(`/api/projects/${id}`,'DELETE')).status,200);assert.equal((await f.request(`/api/projects/${id}`)).status,404);
}finally{await f.close()}});

test('uploads validate magic bytes, persist media and reject cross-project references',async()=>{const f=await fixture();try{
  const p=f.store.createProject('素材项目'),other=f.store.createProject('其他项目');let form=new FormData();form.append('file',new Blob([png],{type:'image/png'}),'图片.png');const uploaded=await f.request(`/api/projects/${p.id}/assets`,'POST',form);assert.equal(uploaded.status,201);const asset=uploaded.body.asset;assert.equal(asset.kind,'image');assert.equal((await fetch(f.base+asset.url)).status,200);
  const c:CanvasDocument={...canvas(),nodes:[{...node(),data:{kind:'image',title:'参考',prompt:'',assetId:asset.id,url:asset.url}}]};assert.equal((await f.request(`/api/projects/${p.id}/canvas`,'PUT',c)).status,200);assert.equal((await f.request(`/api/projects/${other.id}/canvas`,'PUT',c)).status,400);
  form=new FormData();form.append('file',new Blob(['<script>alert(1)</script>'],{type:'image/png'}),'fake.png');assert.equal((await f.request(`/api/projects/${p.id}/assets`,'POST',form)).status,415);
  await f.request(`/api/projects/${p.id}`,'DELETE');assert.equal((await fetch(f.base+asset.url)).status,404);
}finally{await f.close()}});

test('missing services fail before creating paid jobs or incomplete Agent conversations',async()=>{const f=await fixture();try{const p=f.store.createProject();f.store.saveCanvas(p.id,canvas());const status=await f.request('/api/status');assert.equal(status.body.services.text.configured,false);const generation=await f.request(`/api/projects/${p.id}/nodes/text-one/generate`,'POST',{});assert.equal(generation.status,503);assert.match(generation.body.error,/尚未配置/);assert.equal(f.store.jobs(p.id).length,0);const response=await f.request(`/api/projects/${p.id}/agent`,'POST',{message:'把第二个镜头改成近景'});assert.equal(response.status,503);assert.equal(f.store.messages(p.id).length,0)}finally{await f.close()}});

test('workspace authentication, session cookies and same-origin mutations protect data',async()=>{const f=await fixture({ACCESS_PASSWORD:'local-test-password'});try{assert.equal((await f.request('/api/status')).body.authRequired,true);assert.equal((await f.request('/api/projects')).status,401);assert.equal((await f.request('/api/auth/login','POST',{password:'wrong'})).status,401);const login=await f.request('/api/auth/login','POST',{password:'local-test-password'});assert.equal(login.status,200);const cookie=login.response.headers.get('set-cookie')!.split(';')[0];assert.match(login.response.headers.get('set-cookie')!,/HttpOnly/);assert.equal((await f.request('/api/projects','POST',{name:'受保护项目'},cookie)).status,201);const cross=await fetch(f.base+'/api/projects',{method:'POST',headers:{Cookie:cookie,Origin:'https://attacker.example','Content-Type':'application/json'},body:'{}'});assert.equal(cross.status,403);await f.request('/api/auth/logout','POST',{},cookie);assert.equal((await f.request('/api/projects','GET',undefined,cookie)).status,401)}finally{await f.close()}});

test('secrets are encrypted at rest and never appear in status responses',async()=>{const f=await fixture();try{const key='test-secret-not-a-real-credential';const response=await f.request('/api/settings','PUT',{textBaseUrl:'https://provider.example/v1',textKey:key,textModel:'test-model'});assert.equal(response.status,200);assert.equal(response.body.services.text.configured,true);assert.ok(!JSON.stringify(response.body).includes(key));assert.ok(!f.store.setting('providers')!.includes(key));assert.ok(!readFileSync(path.join(f.dir,'studio.sqlite')).includes(Buffer.from(key)));const another=new Configuration(f.store,{});assert.equal(another.settings().textKey,key);await f.request('/api/settings','PUT',{textKey:'',textModel:'test-model-two'});assert.equal(f.config.settings().textKey,key)}finally{await f.close()}});

test('Agent tool validation updates only requested shot and prevents cross-project tools',async()=>{const f=await fixture();try{const p=f.store.createProject(),q=f.store.createProject();f.store.saveCanvas(p.id,{...canvas(),nodes:[{...node('shot1'),data:{...node().data,shotNumber:1}},{...node('shot2'),data:{...node().data,shotNumber:2}}]});f.store.saveCanvas(q.id,canvas([node('other-node')]));f.agent.executeTool(p.id,'update_node',{nodeId:'shot2',prompt:'杯沿特写，镜头近景'},'test-run');assert.equal(f.store.canvas(p.id).nodes[0].data.prompt,'拍摄一杯咖啡');assert.equal(f.store.canvas(p.id).nodes[1].data.prompt,'杯沿特写，镜头近景');assert.throws(()=>f.agent.executeTool(p.id,'update_node',{nodeId:'other-node',prompt:'不允许'},'run'),/不存在/);assert.throws(()=>f.agent.executeTool(p.id,'create_node',{kind:'image',title:'危险',prompt:'',url:'https://example.com/fake.png'},'run'));assert.throws(()=>f.agent.executeTool(p.id,'delete_project',{},'run'),/不支持/);assert.throws(()=>f.agent.executeTool(p.id,'connect_nodes',{source:'shot1',target:'other-node'},'run'),/当前项目/)}finally{await f.close()}});

test('local mock gateway SSE decodes fragmented tool arguments and omits sys_name',async()=>{let received:any;const server=createServer((req,res)=>{received=req.headers;res.writeHead(200,{'Content-Type':'text/event-stream'});for(const chunk of [{choices:[{delta:{content:'分镜'}}]},{choices:[{delta:{tool_calls:[{index:0,id:'call-1',function:{name:'update_node',arguments:'{"nodeId":"shot2",'}}]}}]},{choices:[{delta:{tool_calls:[{index:0,function:{arguments:'"prompt":"近景"}'}}]},finish_reason:'tool_calls'}]}])res.write(`data: ${JSON.stringify(chunk)}\n\n`);res.end('data: [DONE]\n\n')});server.listen(0,'127.0.0.1');await new Promise<void>(r=>server.once('listening',r));try{const result=await chat({protocol:'openai',kind:'text',baseUrl:`http://127.0.0.1:${(server.address() as AddressInfo).port}`,key:'local-test',model:'local-mock'},[{role:'user',content:'test'}]);assert.equal(result.content,'分镜');assert.equal(JSON.parse(result.toolCalls[0].function.arguments).prompt,'近景');assert.equal(received.sys_name,undefined);assert.equal(received.authorization,'Bearer local-test')}finally{await new Promise<void>(r=>server.close(()=>r()))}});

test('local mock generation is durable, idempotent, and writes generated text to the saved node',async()=>{let requests=0;const provider=createServer((_req,res)=>{requests++;res.writeHead(200,{'Content-Type':'text/event-stream'});res.end('data: {"choices":[{"delta":{"content":"本地测试生成内容"},"finish_reason":"stop"}]}\n\ndata: [DONE]\n\n')});provider.listen(0,'127.0.0.1');await new Promise<void>(r=>provider.once('listening',r));const f=await fixture({TEXT_API_KEY:'local-test',TEXT_MODEL:'local-mock',TEXT_BASE_URL:`http://127.0.0.1:${(provider.address() as AddressInfo).port}`});try{const p=f.store.createProject();f.store.saveCanvas(p.id,canvas());const a=await f.request(`/api/projects/${p.id}/nodes/text-one/generate`,'POST',{idempotencyKey:'same-key'});const b=await f.request(`/api/projects/${p.id}/nodes/text-one/generate`,'POST',{idempotencyKey:'same-key'});assert.equal(a.body.job.id,b.body.job.id);await until(()=>f.store.job(a.body.job.id).status==='succeeded');assert.equal(requests,1);assert.equal(f.store.canvas(p.id).nodes[0].data.text,'本地测试生成内容');assert.equal(f.store.canvas(p.id).nodes[0].data.status,'succeeded')}finally{await f.close();await new Promise<void>(r=>provider.close(()=>r()))}});

test('restart recovers ambiguous submission without automatically retrying a paid request',async()=>{const f=await fixture();try{const p=f.store.createProject();f.store.saveCanvas(p.id,canvas());const job=f.store.insertJob(p.id,'text-one','text',{prompt:'test'},f.config.encrypt({protocol:'openai',kind:'text',baseUrl:'http://127.0.0.1:1',key:'local-test',model:'mock'}),'test');f.store.updateJob(job.id,{status:'running',phase:'submitting'});const engine=new JobEngine(f.store,f.config);engine.recover();const recovered=f.store.job(job.id);assert.equal(recovered.status,'failed');assert.equal(recovered.ambiguous,1);assert.match(recovered.error!,/不会自动重复提交/);assert.throws(()=>engine.create(p.id,'text-one','different-key'),/不确定/);engine.stop()}finally{await f.close()}});
